### ISSUE TITLE
error when run the evaluation.py with trained model

### ISSUE THREAD

**Issue by dogyoonlee** [zl548/Neural-Scene-Flow-Fields#23]
![image](https://user-images.githubusercontent.com/62277785/134349373-b05723ef-be7d-4d85-add2-3b19f31d113d.png)

Hello, I really appreciate to your awesome work!!

However, I have an error when I try to run the `evaluation.py` file with our trained model.

I think there are lack of declaration on `--chain_sf` in the file.

I used the given configuration file of kid-running scene.

Here are script that I run

```
python evaluation.py --datadir /data1/dogyoon/neural_sceneflow_data/nerf_data/kid-running/dense/ --expname Default_Test --config configs/config_kid-running.txt
```

Do I  should add the argument in evaluation.py file or there are any way to solve this problem?

Thanks!!

**Comment by fuqichen1998** [comment]
I have the same issue. Did you solve it?

**Comment by owang** [comment]
I believe this is a parameter that is used only during training and not evaluation. Does it work if you add the param to the evaluation file but then do nothing with it just to remove the error: e.g., by adding: 

```
parser.add_argument("--chain_sf", action='store_true', help='unused')
```

**Comment by fuqichen1998** [comment]
Yes, it works! Thanks for your help!
